title: ELA Consultoria
email: contato@elaconsultoria.com.br
description: Formada por uma equipe interdisciplinar, a Ela Consultoria Tem a missão de multiplicar conhecimentos aos profissionais ligados diretos ou indiretamente envolvidos com a correta aplicação das legislações trabalhistas e previdenciárias nas rotinas pertinentes ao departamento pessoal.
baseurl: ""
url: ""

company_name: ELA Consultoria
address_line: Rio de Janeiro - RJ
telephone_number: (21) 972926848
fax_number: (21) 972926848
company_email: contato@elaconsultoria.com.br
google_map: https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3618.727010735933!2d91.837871!3d24.907291700000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1404919738144

facebook_link: http://www.facebook.com/elaconsultoria.com.br
instagram_link: http://www.facebook.com/elaconsultoria29072019
medium_link: http://medium.com/@elaconsultoria
twitter_link: http://www.twitter.com/elaconsultoria
linkedin_link: http://www.linkedin.com/elaconsultoria

markdown: kramdown
plugins:
  - jekyll-feed
